// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/14/2025, 2:08:57 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Admin/Desktop/project-bolt-sb1-m6lavhab/project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/project-bolt-sb1-m6lavhab/project/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/project-bolt-sb1-m6lavhab/project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/project-bolt-sb1-m6lavhab/project/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/project-bolt-sb1-m6lavhab/project/plugins/**/*.{js,ts,mjs}","C:/Users/Admin/Desktop/project-bolt-sb1-m6lavhab/project/composables/**/*.{js,ts,mjs}","C:/Users/Admin/Desktop/project-bolt-sb1-m6lavhab/project/utils/**/*.{js,ts,mjs}","C:/Users/Admin/Desktop/project-bolt-sb1-m6lavhab/project/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/project-bolt-sb1-m6lavhab/project/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/project-bolt-sb1-m6lavhab/project/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/project-bolt-sb1-m6lavhab/project/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;