// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/5/2025, 8:12:35 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Admin/Desktop/Final/Pharmacy Website/project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/Final/Pharmacy Website/project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/Final/Pharmacy Website/project/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/Final/Pharmacy Website/project/plugins/**/*.{js,ts,mjs}","C:/Users/Admin/Desktop/Final/Pharmacy Website/project/stores/**/*.{js,ts,mjs}","C:/Users/Admin/Desktop/Final/Pharmacy Website/project/composables/**/*.{js,ts,mjs}","C:/Users/Admin/Desktop/Final/Pharmacy Website/project/utils/**/*.{js,ts,mjs}","C:/Users/Admin/Desktop/Final/Pharmacy Website/project/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/Final/Pharmacy Website/project/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/Final/Pharmacy Website/project/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/Final/Pharmacy Website/project/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;