// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/5/2025, 11:26:05 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Admin/Desktop/longchau_pms/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/longchau_pms/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/longchau_pms/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/longchau_pms/plugins/**/*.{js,ts,mjs}","C:/Users/Admin/Desktop/longchau_pms/stores/**/*.{js,ts,mjs}","C:/Users/Admin/Desktop/longchau_pms/composables/**/*.{js,ts,mjs}","C:/Users/Admin/Desktop/longchau_pms/utils/**/*.{js,ts,mjs}","C:/Users/Admin/Desktop/longchau_pms/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/longchau_pms/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/longchau_pms/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Admin/Desktop/longchau_pms/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;